### PR TITLE
Contrib

### PR DESCRIPTION
**Pull request by ghost**
Applying enhancements from https://github.com/miyo-eficode/docker-images and some cleanups
- increased noninteractivity to prevent package installation failures
- combine operations to reduce amount of layers, because there is a limit
- some trimming operations to make it smaller (not so much, but some)
- always update packages, so you get latest security patches

### CODE REVIEW

**Comment by chaggeus** [comment]
Nice. There is many important changes what I forger. My opinion is that this could accepted.

**Comment by walhava** [comment]
@miyo-eficode thanks, I'd like to see the contributors in order of contribution instead of alphabetic order. afterthat I can accept.

**Comment by ghost** [comment]
Changes have been done in small "logical" bits, hence you can easily manage which parts you want to include or if you want to revert some changes. On my behalf you can set the contributors in any order you want.

**Comment by walhava** [comment]
@miyo-eficode @chaggeus is now merged, thanks for the input!

**Pull request merged**
